import { getSupportedToolLocale, type SupportedToolLocale } from "./tool-locale"

const ENGLISH_COPY = {
  close: "Close",
  pending: "pending",
  error: "error",
  completed: "completed",
  status: "Status",
  result: "Result",
  errorDetails: "Error details",
  input: "Input",
  output: "Output",
  type: "Type",
  generatedFiles: "Generated files",
  file: "file",
  files: "files",
  resource: "Resource",
  resources: "Resources",
  datasourceResources: "Datasource resources",
  view: "View",
  openingResource: "Opening resource…",
  resourceOpenFailed: "Unable to open resource. Try again.",
  searching: "Searching…",
  searchResults: "Search results",
  searchingForSources: "Searching for sources…",
  noSourcesReturned: "No sources returned.",
  agent: "Agent",
  agentInvocationResult: "Agent invocation result",
  agentId: "Agent ID",
  executionId: "Execution ID",
  threadId: "Thread ID",
  prompt: "Prompt",
  openConversation: "Open conversation",
  workflow: "Workflow",
  workflowDispatch: "Workflow dispatch",
  workflowDispatchResult: "Workflow dispatch result",
  workflowId: "Workflow ID",
  mcpTool: "MCP tool",
  mcpToolResult: "MCP tool result",
  tool: "Tool",
  server: "Server",
  officeDocuments: "Office documents",
  creatingDocuments: "Creating documents…",
  noFilesGenerated: "No files were generated.",
  httpRequest: "HTTP request",
  httpResponse: "HTTP response",
  requestUrl: "Request URL",
  responseUrl: "Response URL",
  contentType: "Content type",
  response: "Response",
  responseHeaders: "Response headers",
  externalDatasource: "External datasource",
  externalDatasourceResult: "External datasource result",
  sqlQuery: "SQL query",
  queryResults: "Query results",
  noDataToDisplay: "No data to display.",
  property: "Property",
  value: "Value",
  browser: "Browser",
  browserResult: "Browser result",
  expandBrowserResult: "Expand browser result",
  collapseBrowserResult: "Collapse browser result",
  credit: "credit",
  credits: "credits",
  email: "Email",
  subject: "Subject",
  to: "To",
  noRecipientsProvided: "No recipients provided.",
  body: "Body",
  delivery: "Delivery",
  recipients: "Recipients",
  provider: "Provider",
  messageId: "Message ID",
  rawStatus: "Raw status",
  typeMessage: "Type a message...",
  send: "Send",
  stop: "Stop",
  attachFile: "Attach file",
  removeFile: "Remove file",
  uploading: "Uploading",
  processingUpload: "Processing upload",
  uploadFailed: "Upload failed",
  thinking: "Thinking…",
  thoughtProcess: "Thought process",
  collapse: "Collapse",
  expand: "Expand",
  thinkingInProgress: "Thinking in progress",
  thinkingComplete: "Thinking complete",
  uploadedImage: "Uploaded image",
  document: "Document",
  readMore: "Read more",
  readLess: "Read less",
  copy: "Copy",
  copied: "Copied",
  retryResponse: "Retry response",
  ratePositively: "Rate positively",
  rateNegatively: "Rate negatively",
  voiceInput: "Voice input",
  stopRecording: "Stop recording",
  cancelRecording: "Cancel recording",
  requestingMicrophoneAccess: "Requesting microphone access...",
  transcribing: "Transcribing...",
}

export type UiCopy = typeof ENGLISH_COPY

const SPANISH_COPY: Partial<UiCopy> = {
  close: "Cerrar",
  pending: "pendiente",
  error: "error",
  completed: "completado",
  status: "Estado",
  result: "Resultado",
  errorDetails: "Detalles del error",
  input: "Entrada",
  output: "Salida",
  type: "Tipo",
  generatedFiles: "Archivos generados",
  file: "archivo",
  files: "archivos",
  resource: "Recurso",
  resources: "Recursos",
  datasourceResources: "Recursos de la fuente de datos",
  view: "Ver",
  openingResource: "Abriendo recurso…",
  resourceOpenFailed: "No se pudo abrir el recurso. Inténtalo de nuevo.",
  searching: "Buscando…",
  searchResults: "Resultados de búsqueda",
  searchingForSources: "Buscando fuentes…",
  noSourcesReturned: "No se encontraron fuentes.",
  agent: "Agente",
  agentInvocationResult: "Resultado de la invocación del agente",
  agentId: "ID del agente",
  executionId: "ID de ejecución",
  threadId: "ID de conversación",
  prompt: "Instrucción",
  openConversation: "Abrir conversación",
  workflow: "Flujo de trabajo",
  workflowDispatch: "Ejecución del flujo de trabajo",
  workflowDispatchResult: "Resultado del flujo de trabajo",
  workflowId: "ID del flujo de trabajo",
  mcpTool: "Herramienta MCP",
  mcpToolResult: "Resultado de la herramienta MCP",
  tool: "Herramienta",
  server: "Servidor",
  officeDocuments: "Documentos de Office",
  creatingDocuments: "Creando documentos…",
  noFilesGenerated: "No se generaron archivos.",
  httpRequest: "Solicitud HTTP",
  httpResponse: "Respuesta HTTP",
  requestUrl: "URL de la solicitud",
  responseUrl: "URL de la respuesta",
  contentType: "Tipo de contenido",
  response: "Respuesta",
  responseHeaders: "Encabezados de respuesta",
  externalDatasource: "Fuente de datos externa",
  externalDatasourceResult: "Resultado de la fuente de datos externa",
  sqlQuery: "Consulta SQL",
  queryResults: "Resultados de la consulta",
  noDataToDisplay: "No hay datos que mostrar.",
  property: "Propiedad",
  value: "Valor",
  browser: "Navegador",
  browserResult: "Resultado del navegador",
  expandBrowserResult: "Expandir resultado del navegador",
  collapseBrowserResult: "Contraer resultado del navegador",
  credit: "crédito",
  credits: "créditos",
  email: "Correo electrónico",
  subject: "Asunto",
  to: "Para",
  noRecipientsProvided: "No se indicaron destinatarios.",
  body: "Cuerpo",
  delivery: "Entrega",
  recipients: "Destinatarios",
  provider: "Proveedor",
  messageId: "ID del mensaje",
  rawStatus: "Estado original",
  typeMessage: "Escribe un mensaje...",
  send: "Enviar",
  stop: "Detener",
  attachFile: "Adjuntar archivo",
  removeFile: "Quitar archivo",
  uploading: "Subiendo",
  processingUpload: "Procesando archivo",
  uploadFailed: "Error al subir el archivo",
  thinking: "Pensando…",
  thoughtProcess: "Proceso de razonamiento",
  collapse: "Contraer",
  expand: "Expandir",
  thinkingInProgress: "Pensando",
  thinkingComplete: "Pensamiento completado",
  uploadedImage: "Imagen subida",
  document: "Documento",
  readMore: "Leer más",
  readLess: "Leer menos",
  copy: "Copiar",
  copied: "Copiado",
  retryResponse: "Reintentar respuesta",
  ratePositively: "Valorar positivamente",
  rateNegatively: "Valorar negativamente",
  voiceInput: "Entrada de voz",
  stopRecording: "Detener grabación",
  cancelRecording: "Cancelar grabación",
  requestingMicrophoneAccess: "Solicitando acceso al micrófono...",
  transcribing: "Transcribiendo...",
}

const CATALAN_COPY: Partial<UiCopy> = {
  close: "Tanca",
  pending: "pendent",
  error: "error",
  completed: "completat",
  status: "Estat",
  result: "Resultat",
  errorDetails: "Detalls de l’error",
  input: "Entrada",
  output: "Sortida",
  type: "Tipus",
  generatedFiles: "Fitxers generats",
  file: "fitxer",
  files: "fitxers",
  resource: "Recurs",
  resources: "Recursos",
  datasourceResources: "Recursos de la font de dades",
  view: "Mostra",
  openingResource: "Obrint el recurs…",
  resourceOpenFailed: "No s’ha pogut obrir el recurs. Torna-ho a provar.",
  searching: "Cercant…",
  searchResults: "Resultats de cerca",
  searchingForSources: "Cercant fonts…",
  noSourcesReturned: "No s’han trobat fonts.",
  agent: "Agent",
  agentInvocationResult: "Resultat de la invocació de l’agent",
  agentId: "ID de l’agent",
  executionId: "ID d’execució",
  threadId: "ID de la conversa",
  prompt: "Instrucció",
  openConversation: "Obre la conversa",
  workflow: "Flux de treball",
  workflowDispatch: "Execució del flux de treball",
  workflowDispatchResult: "Resultat del flux de treball",
  workflowId: "ID del flux de treball",
  mcpTool: "Eina MCP",
  mcpToolResult: "Resultat de l’eina MCP",
  tool: "Eina",
  server: "Servidor",
  officeDocuments: "Documents d’Office",
  creatingDocuments: "Creant documents…",
  noFilesGenerated: "No s’han generat fitxers.",
  httpRequest: "Sol·licitud HTTP",
  httpResponse: "Resposta HTTP",
  requestUrl: "URL de la sol·licitud",
  responseUrl: "URL de la resposta",
  contentType: "Tipus de contingut",
  response: "Resposta",
  responseHeaders: "Capçaleres de la resposta",
  externalDatasource: "Font de dades externa",
  externalDatasourceResult: "Resultat de la font de dades externa",
  sqlQuery: "Consulta SQL",
  queryResults: "Resultats de la consulta",
  noDataToDisplay: "No hi ha dades per mostrar.",
  property: "Propietat",
  value: "Valor",
  browser: "Navegador",
  browserResult: "Resultat del navegador",
  expandBrowserResult: "Desplega el resultat del navegador",
  collapseBrowserResult: "Plega el resultat del navegador",
  credit: "crèdit",
  credits: "crèdits",
  email: "Correu electrònic",
  subject: "Assumpte",
  to: "Per a",
  noRecipientsProvided: "No s’han indicat destinataris.",
  body: "Cos",
  delivery: "Lliurament",
  recipients: "Destinataris",
  provider: "Proveïdor",
  messageId: "ID del missatge",
  rawStatus: "Estat original",
  typeMessage: "Escriu un missatge...",
  send: "Envia",
  stop: "Atura",
  attachFile: "Adjunta un fitxer",
  removeFile: "Elimina el fitxer",
  uploading: "Pujant",
  processingUpload: "Processant el fitxer",
  uploadFailed: "No s’ha pogut pujar el fitxer",
  thinking: "Pensant…",
  thoughtProcess: "Procés de raonament",
  collapse: "Plega",
  expand: "Desplega",
  thinkingInProgress: "Pensant",
  thinkingComplete: "Raonament completat",
  uploadedImage: "Imatge pujada",
  document: "Document",
  readMore: "Llegeix més",
  readLess: "Llegeix menys",
  copy: "Copia",
  copied: "Copiat",
  retryResponse: "Torna a provar la resposta",
  ratePositively: "Valora positivament",
  rateNegatively: "Valora negativament",
  voiceInput: "Entrada de veu",
  stopRecording: "Atura la gravació",
  cancelRecording: "Cancel·la la gravació",
  requestingMicrophoneAccess: "Sol·licitant accés al micròfon...",
  transcribing: "Transcrivint...",
}

const FRENCH_COPY: Partial<UiCopy> = {
  close: "Fermer",
  pending: "en attente",
  error: "erreur",
  completed: "terminé",
  status: "Statut",
  result: "Résultat",
  errorDetails: "Détails de l’erreur",
  input: "Entrée",
  output: "Sortie",
  type: "Type",
  generatedFiles: "Fichiers générés",
  file: "fichier",
  files: "fichiers",
  resource: "Ressource",
  resources: "Ressources",
  datasourceResources: "Ressources de la source de données",
  view: "Voir",
  openingResource: "Ouverture de la ressource…",
  resourceOpenFailed: "Impossible d’ouvrir la ressource. Réessayez.",
  searching: "Recherche…",
  searchResults: "Résultats de recherche",
  searchingForSources: "Recherche de sources…",
  noSourcesReturned: "Aucune source trouvée.",
  agent: "Agent",
  agentInvocationResult: "Résultat de l’exécution de l’agent",
  agentId: "ID de l’agent",
  executionId: "ID d’exécution",
  threadId: "ID de la conversation",
  prompt: "Instruction",
  openConversation: "Ouvrir la conversation",
  workflow: "Flux de travail",
  workflowDispatch: "Exécution du flux de travail",
  workflowDispatchResult: "Résultat du flux de travail",
  workflowId: "ID du flux de travail",
  mcpTool: "Outil MCP",
  mcpToolResult: "Résultat de l’outil MCP",
  tool: "Outil",
  server: "Serveur",
  officeDocuments: "Documents Office",
  creatingDocuments: "Création des documents…",
  noFilesGenerated: "Aucun fichier n’a été généré.",
  httpRequest: "Requête HTTP",
  httpResponse: "Réponse HTTP",
  requestUrl: "URL de la requête",
  responseUrl: "URL de la réponse",
  contentType: "Type de contenu",
  response: "Réponse",
  responseHeaders: "En-têtes de réponse",
  externalDatasource: "Source de données externe",
  externalDatasourceResult: "Résultat de la source de données externe",
  sqlQuery: "Requête SQL",
  queryResults: "Résultats de la requête",
  noDataToDisplay: "Aucune donnée à afficher.",
  property: "Propriété",
  value: "Valeur",
  browser: "Navigateur",
  browserResult: "Résultat du navigateur",
  expandBrowserResult: "Développer le résultat du navigateur",
  collapseBrowserResult: "Réduire le résultat du navigateur",
  credit: "crédit",
  credits: "crédits",
  email: "E-mail",
  subject: "Objet",
  to: "À",
  noRecipientsProvided: "Aucun destinataire indiqué.",
  body: "Corps du message",
  delivery: "Envoi",
  recipients: "Destinataires",
  provider: "Fournisseur",
  messageId: "ID du message",
  rawStatus: "Statut brut",
  typeMessage: "Saisissez un message...",
  send: "Envoyer",
  stop: "Arrêter",
  attachFile: "Joindre un fichier",
  removeFile: "Supprimer le fichier",
  uploading: "Téléversement",
  processingUpload: "Traitement du fichier",
  uploadFailed: "Échec du téléversement",
  thinking: "Réflexion…",
  thoughtProcess: "Processus de réflexion",
  collapse: "Réduire",
  expand: "Développer",
  thinkingInProgress: "Réflexion en cours",
  thinkingComplete: "Réflexion terminée",
  uploadedImage: "Image téléversée",
  document: "Document",
  readMore: "Lire la suite",
  readLess: "Lire moins",
  copy: "Copier",
  copied: "Copié",
  retryResponse: "Réessayer la réponse",
  ratePositively: "Évaluer positivement",
  rateNegatively: "Évaluer négativement",
  voiceInput: "Saisie vocale",
  stopRecording: "Arrêter l’enregistrement",
  cancelRecording: "Annuler l’enregistrement",
  requestingMicrophoneAccess: "Demande d’accès au microphone...",
  transcribing: "Transcription en cours...",
}

const ITALIAN_COPY: Partial<UiCopy> = {
  close: "Chiudi",
  pending: "in attesa",
  error: "errore",
  completed: "completato",
  status: "Stato",
  result: "Risultato",
  errorDetails: "Dettagli dell’errore",
  input: "Input",
  output: "Output",
  type: "Tipo",
  generatedFiles: "File generati",
  file: "file",
  files: "file",
  resource: "Risorsa",
  resources: "Risorse",
  datasourceResources: "Risorse della fonte dati",
  view: "Visualizza",
  openingResource: "Apertura della risorsa…",
  resourceOpenFailed: "Impossibile aprire la risorsa. Riprova.",
  searching: "Ricerca…",
  searchResults: "Risultati della ricerca",
  searchingForSources: "Ricerca delle fonti…",
  noSourcesReturned: "Nessuna fonte trovata.",
  agent: "Agente",
  agentInvocationResult: "Risultato dell’esecuzione dell’agente",
  agentId: "ID dell’agente",
  executionId: "ID esecuzione",
  threadId: "ID conversazione",
  prompt: "Istruzione",
  openConversation: "Apri conversazione",
  workflow: "Flusso di lavoro",
  workflowDispatch: "Esecuzione del flusso di lavoro",
  workflowDispatchResult: "Risultato del flusso di lavoro",
  workflowId: "ID del flusso di lavoro",
  mcpTool: "Strumento MCP",
  mcpToolResult: "Risultato dello strumento MCP",
  tool: "Strumento",
  server: "Server",
  officeDocuments: "Documenti Office",
  creatingDocuments: "Creazione dei documenti…",
  noFilesGenerated: "Nessun file generato.",
  httpRequest: "Richiesta HTTP",
  httpResponse: "Risposta HTTP",
  requestUrl: "URL della richiesta",
  responseUrl: "URL della risposta",
  contentType: "Tipo di contenuto",
  response: "Risposta",
  responseHeaders: "Intestazioni della risposta",
  externalDatasource: "Fonte dati esterna",
  externalDatasourceResult: "Risultato della fonte dati esterna",
  sqlQuery: "Query SQL",
  queryResults: "Risultati della query",
  noDataToDisplay: "Nessun dato da visualizzare.",
  property: "Proprietà",
  value: "Valore",
  browser: "Browser",
  browserResult: "Risultato del browser",
  expandBrowserResult: "Espandi il risultato del browser",
  collapseBrowserResult: "Comprimi il risultato del browser",
  credit: "credito",
  credits: "crediti",
  email: "Email",
  subject: "Oggetto",
  to: "A",
  noRecipientsProvided: "Nessun destinatario indicato.",
  body: "Corpo",
  delivery: "Invio",
  recipients: "Destinatari",
  provider: "Fornitore",
  messageId: "ID messaggio",
  rawStatus: "Stato originale",
  typeMessage: "Scrivi un messaggio...",
  send: "Invia",
  stop: "Interrompi",
  attachFile: "Allega un file",
  removeFile: "Rimuovi il file",
  uploading: "Caricamento",
  processingUpload: "Elaborazione del file",
  uploadFailed: "Caricamento non riuscito",
  thinking: "Riflessione…",
  thoughtProcess: "Processo di ragionamento",
  collapse: "Comprimi",
  expand: "Espandi",
  thinkingInProgress: "Riflessione in corso",
  thinkingComplete: "Riflessione completata",
  uploadedImage: "Immagine caricata",
  document: "Documento",
  readMore: "Leggi di più",
  readLess: "Leggi meno",
  copy: "Copia",
  copied: "Copiato",
  retryResponse: "Riprova la risposta",
  ratePositively: "Valuta positivamente",
  rateNegatively: "Valuta negativamente",
  voiceInput: "Input vocale",
  stopRecording: "Interrompi la registrazione",
  cancelRecording: "Annulla la registrazione",
  requestingMicrophoneAccess: "Richiesta di accesso al microfono...",
  transcribing: "Trascrizione in corso...",
}

const PORTUGUESE_COPY: Partial<UiCopy> = {
  close: "Fechar",
  pending: "pendente",
  error: "erro",
  completed: "concluído",
  status: "Estado",
  result: "Resultado",
  errorDetails: "Detalhes do erro",
  input: "Entrada",
  output: "Saída",
  type: "Tipo",
  generatedFiles: "Ficheiros gerados",
  file: "ficheiro",
  files: "ficheiros",
  resource: "Recurso",
  resources: "Recursos",
  datasourceResources: "Recursos da fonte de dados",
  view: "Ver",
  openingResource: "A abrir o recurso…",
  resourceOpenFailed: "Não foi possível abrir o recurso. Tente novamente.",
  searching: "A pesquisar…",
  searchResults: "Resultados da pesquisa",
  searchingForSources: "A pesquisar fontes…",
  noSourcesReturned: "Não foram encontradas fontes.",
  agent: "Agente",
  agentInvocationResult: "Resultado da execução do agente",
  agentId: "ID do agente",
  executionId: "ID de execução",
  threadId: "ID da conversa",
  prompt: "Instrução",
  openConversation: "Abrir conversa",
  workflow: "Fluxo de trabalho",
  workflowDispatch: "Execução do fluxo de trabalho",
  workflowDispatchResult: "Resultado do fluxo de trabalho",
  workflowId: "ID do fluxo de trabalho",
  mcpTool: "Ferramenta MCP",
  mcpToolResult: "Resultado da ferramenta MCP",
  tool: "Ferramenta",
  server: "Servidor",
  officeDocuments: "Documentos do Office",
  creatingDocuments: "A criar documentos…",
  noFilesGenerated: "Não foram gerados ficheiros.",
  httpRequest: "Pedido HTTP",
  httpResponse: "Resposta HTTP",
  requestUrl: "URL do pedido",
  responseUrl: "URL da resposta",
  contentType: "Tipo de conteúdo",
  response: "Resposta",
  responseHeaders: "Cabeçalhos da resposta",
  externalDatasource: "Fonte de dados externa",
  externalDatasourceResult: "Resultado da fonte de dados externa",
  sqlQuery: "Consulta SQL",
  queryResults: "Resultados da consulta",
  noDataToDisplay: "Não há dados para apresentar.",
  property: "Propriedade",
  value: "Valor",
  browser: "Navegador",
  browserResult: "Resultado do navegador",
  expandBrowserResult: "Expandir resultado do navegador",
  collapseBrowserResult: "Recolher resultado do navegador",
  credit: "crédito",
  credits: "créditos",
  email: "E-mail",
  subject: "Assunto",
  to: "Para",
  noRecipientsProvided: "Não foram indicados destinatários.",
  body: "Corpo",
  delivery: "Entrega",
  recipients: "Destinatários",
  provider: "Fornecedor",
  messageId: "ID da mensagem",
  rawStatus: "Estado original",
  typeMessage: "Escreva uma mensagem...",
  send: "Enviar",
  stop: "Parar",
  attachFile: "Anexar ficheiro",
  removeFile: "Remover ficheiro",
  uploading: "A carregar",
  processingUpload: "A processar o ficheiro",
  uploadFailed: "Falha ao carregar o ficheiro",
  thinking: "A pensar…",
  thoughtProcess: "Processo de raciocínio",
  collapse: "Recolher",
  expand: "Expandir",
  thinkingInProgress: "Raciocínio em curso",
  thinkingComplete: "Raciocínio concluído",
  uploadedImage: "Imagem carregada",
  document: "Documento",
  readMore: "Ler mais",
  readLess: "Ler menos",
  copy: "Copiar",
  copied: "Copiado",
  retryResponse: "Tentar novamente a resposta",
  ratePositively: "Avaliar positivamente",
  rateNegatively: "Avaliar negativamente",
  voiceInput: "Entrada de voz",
  stopRecording: "Parar gravação",
  cancelRecording: "Cancelar gravação",
  requestingMicrophoneAccess: "A pedir acesso ao microfone...",
  transcribing: "A transcrever...",
}

const GERMAN_COPY: Partial<UiCopy> = {
  close: "Schließen",
  pending: "ausstehend",
  error: "Fehler",
  completed: "abgeschlossen",
  status: "Status",
  result: "Ergebnis",
  errorDetails: "Fehlerdetails",
  input: "Eingabe",
  output: "Ausgabe",
  type: "Typ",
  generatedFiles: "Erstellte Dateien",
  file: "Datei",
  files: "Dateien",
  resource: "Ressource",
  resources: "Ressourcen",
  datasourceResources: "Ressourcen der Datenquelle",
  view: "Anzeigen",
  openingResource: "Ressource wird geöffnet…",
  resourceOpenFailed:
    "Ressource konnte nicht geöffnet werden. Erneut versuchen.",
  searching: "Suche läuft…",
  searchResults: "Suchergebnisse",
  searchingForSources: "Quellen werden gesucht…",
  noSourcesReturned: "Keine Quellen gefunden.",
  agent: "Agent",
  agentInvocationResult: "Ergebnis des Agentenaufrufs",
  agentId: "Agenten-ID",
  executionId: "Ausführungs-ID",
  threadId: "Konversations-ID",
  prompt: "Anweisung",
  openConversation: "Konversation öffnen",
  workflow: "Workflow",
  workflowDispatch: "Workflow-Ausführung",
  workflowDispatchResult: "Ergebnis der Workflow-Ausführung",
  workflowId: "Workflow-ID",
  mcpTool: "MCP-Tool",
  mcpToolResult: "Ergebnis des MCP-Tools",
  tool: "Tool",
  server: "Server",
  officeDocuments: "Office-Dokumente",
  creatingDocuments: "Dokumente werden erstellt…",
  noFilesGenerated: "Es wurden keine Dateien erstellt.",
  httpRequest: "HTTP-Anfrage",
  httpResponse: "HTTP-Antwort",
  requestUrl: "Anfrage-URL",
  responseUrl: "Antwort-URL",
  contentType: "Inhaltstyp",
  response: "Antwort",
  responseHeaders: "Antwort-Header",
  externalDatasource: "Externe Datenquelle",
  externalDatasourceResult: "Ergebnis der externen Datenquelle",
  sqlQuery: "SQL-Abfrage",
  queryResults: "Abfrageergebnisse",
  noDataToDisplay: "Keine Daten zum Anzeigen.",
  property: "Eigenschaft",
  value: "Wert",
  browser: "Browser",
  browserResult: "Browser-Ergebnis",
  expandBrowserResult: "Browser-Ergebnis erweitern",
  collapseBrowserResult: "Browser-Ergebnis einklappen",
  credit: "Guthabenpunkt",
  credits: "Guthabenpunkte",
  email: "E-Mail",
  subject: "Betreff",
  to: "An",
  noRecipientsProvided: "Keine Empfänger angegeben.",
  body: "Nachrichtentext",
  delivery: "Zustellung",
  recipients: "Empfänger",
  provider: "Anbieter",
  messageId: "Nachrichten-ID",
  rawStatus: "Ursprünglicher Status",
  typeMessage: "Nachricht eingeben...",
  send: "Senden",
  stop: "Stoppen",
  attachFile: "Datei anhängen",
  removeFile: "Datei entfernen",
  uploading: "Wird hochgeladen",
  processingUpload: "Datei wird verarbeitet",
  uploadFailed: "Hochladen fehlgeschlagen",
  thinking: "Denkt nach…",
  thoughtProcess: "Denkprozess",
  collapse: "Einklappen",
  expand: "Erweitern",
  thinkingInProgress: "Denkt nach",
  thinkingComplete: "Denken abgeschlossen",
  uploadedImage: "Hochgeladenes Bild",
  document: "Dokument",
  readMore: "Mehr lesen",
  readLess: "Weniger lesen",
  copy: "Kopieren",
  copied: "Kopiert",
  retryResponse: "Antwort erneut versuchen",
  ratePositively: "Positiv bewerten",
  rateNegatively: "Negativ bewerten",
  voiceInput: "Spracheingabe",
  stopRecording: "Aufnahme stoppen",
  cancelRecording: "Aufnahme abbrechen",
  requestingMicrophoneAccess: "Mikrofonzugriff wird angefordert...",
  transcribing: "Wird transkribiert...",
}

const DANISH_COPY: Partial<UiCopy> = {
  close: "Luk",
  pending: "afventer",
  error: "fejl",
  completed: "fuldført",
  status: "Status",
  result: "Resultat",
  errorDetails: "Fejldetaljer",
  input: "Input",
  output: "Output",
  type: "Type",
  generatedFiles: "Genererede filer",
  file: "fil",
  files: "filer",
  resource: "Ressource",
  resources: "Ressourcer",
  datasourceResources: "Datakildens ressourcer",
  view: "Vis",
  openingResource: "Åbner ressource…",
  resourceOpenFailed: "Ressourcen kunne ikke åbnes. Prøv igen.",
  searching: "Søger…",
  searchResults: "Søgeresultater",
  searchingForSources: "Søger efter kilder…",
  noSourcesReturned: "Ingen kilder fundet.",
  agent: "Agent",
  agentInvocationResult: "Resultat af agentkald",
  agentId: "Agent-id",
  executionId: "Udførelses-id",
  threadId: "Samtale-id",
  prompt: "Instruktion",
  openConversation: "Åbn samtale",
  workflow: "Arbejdsgang",
  workflowDispatch: "Udførelse af arbejdsgang",
  workflowDispatchResult: "Resultat af arbejdsgang",
  workflowId: "Arbejdsgangs-id",
  mcpTool: "MCP-værktøj",
  mcpToolResult: "Resultat fra MCP-værktøj",
  tool: "Værktøj",
  server: "Server",
  officeDocuments: "Office-dokumenter",
  creatingDocuments: "Opretter dokumenter…",
  noFilesGenerated: "Ingen filer blev genereret.",
  httpRequest: "HTTP-anmodning",
  httpResponse: "HTTP-svar",
  requestUrl: "Anmodnings-URL",
  responseUrl: "Svar-URL",
  contentType: "Indholdstype",
  response: "Svar",
  responseHeaders: "Svarheadere",
  externalDatasource: "Ekstern datakilde",
  externalDatasourceResult: "Resultat fra ekstern datakilde",
  sqlQuery: "SQL-forespørgsel",
  queryResults: "Forespørgselsresultater",
  noDataToDisplay: "Ingen data at vise.",
  property: "Egenskab",
  value: "Værdi",
  browser: "Browser",
  browserResult: "Browserresultat",
  expandBrowserResult: "Udvid browserresultat",
  collapseBrowserResult: "Skjul browserresultat",
  credit: "kredit",
  credits: "kreditter",
  email: "E-mail",
  subject: "Emne",
  to: "Til",
  noRecipientsProvided: "Ingen modtagere angivet.",
  body: "Indhold",
  delivery: "Levering",
  recipients: "Modtagere",
  provider: "Udbyder",
  messageId: "Besked-id",
  rawStatus: "Oprindelig status",
  typeMessage: "Skriv en besked...",
  send: "Send",
  stop: "Stop",
  attachFile: "Vedhæft fil",
  removeFile: "Fjern fil",
  uploading: "Uploader",
  processingUpload: "Behandler fil",
  uploadFailed: "Upload mislykkedes",
  thinking: "Tænker…",
  thoughtProcess: "Tankeproces",
  collapse: "Skjul",
  expand: "Udvid",
  thinkingInProgress: "Tænker",
  thinkingComplete: "Tænkning afsluttet",
  uploadedImage: "Uploadet billede",
  document: "Dokument",
  readMore: "Læs mere",
  readLess: "Læs mindre",
  copy: "Kopiér",
  copied: "Kopieret",
  retryResponse: "Prøv svaret igen",
  ratePositively: "Bedøm positivt",
  rateNegatively: "Bedøm negativt",
  voiceInput: "Stemmeinput",
  stopRecording: "Stop optagelse",
  cancelRecording: "Annuller optagelse",
  requestingMicrophoneAccess: "Anmoder om adgang til mikrofon...",
  transcribing: "Transskriberer...",
}

const SWEDISH_COPY: Partial<UiCopy> = {
  close: "Stäng",
  pending: "väntar",
  error: "fel",
  completed: "slutförd",
  status: "Status",
  result: "Resultat",
  errorDetails: "Feldetaljer",
  input: "Indata",
  output: "Utdata",
  type: "Typ",
  generatedFiles: "Genererade filer",
  file: "fil",
  files: "filer",
  resource: "Resurs",
  resources: "Resurser",
  datasourceResources: "Datakällans resurser",
  view: "Visa",
  openingResource: "Öppnar resurs…",
  resourceOpenFailed: "Det gick inte att öppna resursen. Försök igen.",
  searching: "Söker…",
  searchResults: "Sökresultat",
  searchingForSources: "Söker efter källor…",
  noSourcesReturned: "Inga källor hittades.",
  agent: "Agent",
  agentInvocationResult: "Resultat från agentanrop",
  agentId: "Agent-ID",
  executionId: "Körnings-ID",
  threadId: "Konversations-ID",
  prompt: "Instruktion",
  openConversation: "Öppna konversation",
  workflow: "Arbetsflöde",
  workflowDispatch: "Körning av arbetsflöde",
  workflowDispatchResult: "Resultat från arbetsflödet",
  workflowId: "Arbetsflödes-ID",
  mcpTool: "MCP-verktyg",
  mcpToolResult: "Resultat från MCP-verktyget",
  tool: "Verktyg",
  server: "Server",
  officeDocuments: "Office-dokument",
  creatingDocuments: "Skapar dokument…",
  noFilesGenerated: "Inga filer genererades.",
  httpRequest: "HTTP-begäran",
  httpResponse: "HTTP-svar",
  requestUrl: "Begärans URL",
  responseUrl: "Svarets URL",
  contentType: "Innehållstyp",
  response: "Svar",
  responseHeaders: "Svarsrubriker",
  externalDatasource: "Extern datakälla",
  externalDatasourceResult: "Resultat från extern datakälla",
  sqlQuery: "SQL-fråga",
  queryResults: "Frågeresultat",
  noDataToDisplay: "Inga data att visa.",
  property: "Egenskap",
  value: "Värde",
  browser: "Webbläsare",
  browserResult: "Webbläsarresultat",
  expandBrowserResult: "Expandera webbläsarresultat",
  collapseBrowserResult: "Dölj webbläsarresultat",
  credit: "kredit",
  credits: "krediter",
  email: "E-post",
  subject: "Ämne",
  to: "Till",
  noRecipientsProvided: "Inga mottagare angavs.",
  body: "Meddelande",
  delivery: "Leverans",
  recipients: "Mottagare",
  provider: "Leverantör",
  messageId: "Meddelande-ID",
  rawStatus: "Ursprunglig status",
  typeMessage: "Skriv ett meddelande...",
  send: "Skicka",
  stop: "Stoppa",
  attachFile: "Bifoga fil",
  removeFile: "Ta bort fil",
  uploading: "Laddar upp",
  processingUpload: "Behandlar fil",
  uploadFailed: "Uppladdningen misslyckades",
  thinking: "Tänker…",
  thoughtProcess: "Tankeprocess",
  collapse: "Dölj",
  expand: "Expandera",
  thinkingInProgress: "Tänker",
  thinkingComplete: "Tänkandet klart",
  uploadedImage: "Uppladdad bild",
  document: "Dokument",
  readMore: "Läs mer",
  readLess: "Läs mindre",
  copy: "Kopiera",
  copied: "Kopierat",
  retryResponse: "Försök med svaret igen",
  ratePositively: "Betygsätt positivt",
  rateNegatively: "Betygsätt negativt",
  voiceInput: "Röstinmatning",
  stopRecording: "Stoppa inspelning",
  cancelRecording: "Avbryt inspelning",
  requestingMicrophoneAccess: "Begär åtkomst till mikrofonen...",
  transcribing: "Transkriberar...",
}

const NORWEGIAN_COPY: Partial<UiCopy> = {
  close: "Lukk",
  pending: "venter",
  error: "feil",
  completed: "fullført",
  status: "Status",
  result: "Resultat",
  errorDetails: "Feildetaljer",
  input: "Inndata",
  output: "Utdata",
  type: "Type",
  generatedFiles: "Genererte filer",
  file: "fil",
  files: "filer",
  resource: "Ressurs",
  resources: "Ressurser",
  datasourceResources: "Datakildens ressurser",
  view: "Vis",
  openingResource: "Åpner ressurs…",
  resourceOpenFailed: "Kunne ikke åpne ressursen. Prøv igjen.",
  searching: "Søker…",
  searchResults: "Søkeresultater",
  searchingForSources: "Søker etter kilder…",
  noSourcesReturned: "Ingen kilder funnet.",
  agent: "Agent",
  agentInvocationResult: "Resultat fra agentkall",
  agentId: "Agent-ID",
  executionId: "Kjørings-ID",
  threadId: "Samtale-ID",
  prompt: "Instruksjon",
  openConversation: "Åpne samtale",
  workflow: "Arbeidsflyt",
  workflowDispatch: "Kjøring av arbeidsflyt",
  workflowDispatchResult: "Resultat fra arbeidsflyten",
  workflowId: "Arbeidsflyt-ID",
  mcpTool: "MCP-verktøy",
  mcpToolResult: "Resultat fra MCP-verktøyet",
  tool: "Verktøy",
  server: "Server",
  officeDocuments: "Office-dokumenter",
  creatingDocuments: "Oppretter dokumenter…",
  noFilesGenerated: "Ingen filer ble generert.",
  httpRequest: "HTTP-forespørsel",
  httpResponse: "HTTP-svar",
  requestUrl: "Forespørsels-URL",
  responseUrl: "Svar-URL",
  contentType: "Innholdstype",
  response: "Svar",
  responseHeaders: "Svarhoder",
  externalDatasource: "Ekstern datakilde",
  externalDatasourceResult: "Resultat fra ekstern datakilde",
  sqlQuery: "SQL-spørring",
  queryResults: "Spørringsresultater",
  noDataToDisplay: "Ingen data å vise.",
  property: "Egenskap",
  value: "Verdi",
  browser: "Nettleser",
  browserResult: "Nettleserresultat",
  expandBrowserResult: "Utvid nettleserresultat",
  collapseBrowserResult: "Skjul nettleserresultat",
  credit: "kreditt",
  credits: "kreditter",
  email: "E-post",
  subject: "Emne",
  to: "Til",
  noRecipientsProvided: "Ingen mottakere oppgitt.",
  body: "Innhold",
  delivery: "Levering",
  recipients: "Mottakere",
  provider: "Leverandør",
  messageId: "Meldings-ID",
  rawStatus: "Opprinnelig status",
  typeMessage: "Skriv en melding...",
  send: "Send",
  stop: "Stopp",
  attachFile: "Legg ved fil",
  removeFile: "Fjern fil",
  uploading: "Laster opp",
  processingUpload: "Behandler fil",
  uploadFailed: "Opplasting mislyktes",
  thinking: "Tenker…",
  thoughtProcess: "Tankeprosess",
  collapse: "Skjul",
  expand: "Utvid",
  thinkingInProgress: "Tenker",
  thinkingComplete: "Tenkingen er ferdig",
  uploadedImage: "Opplastet bilde",
  document: "Dokument",
  readMore: "Les mer",
  readLess: "Les mindre",
  copy: "Kopier",
  copied: "Kopiert",
  retryResponse: "Prøv svaret på nytt",
  ratePositively: "Vurder positivt",
  rateNegatively: "Vurder negativt",
  voiceInput: "Taleinndata",
  stopRecording: "Stopp opptak",
  cancelRecording: "Avbryt opptak",
  requestingMicrophoneAccess: "Ber om tilgang til mikrofonen...",
  transcribing: "Transkriberer...",
}

const TRANSLATIONS: Record<SupportedToolLocale, Partial<UiCopy>> = {
  ca: CATALAN_COPY,
  da: DANISH_COPY,
  de: GERMAN_COPY,
  en: {},
  es: SPANISH_COPY,
  fr: FRENCH_COPY,
  it: ITALIAN_COPY,
  no: NORWEGIAN_COPY,
  pt: PORTUGUESE_COPY,
  sv: SWEDISH_COPY,
}

export function getUiCopy(locale?: string | null): UiCopy {
  return {
    ...ENGLISH_COPY,
    ...TRANSLATIONS[getSupportedToolLocale(locale)],
  }
}

export function getUiStatusLabel(status: string, copy: UiCopy): string {
  if (status === "pending") return copy.pending
  if (status === "error") return copy.error
  if (status === "completed") return copy.completed
  return status
}
